export const poolsData = [
  {
    title: 'MetaGameSpace',
    type: 'static',
    id: 10,
    tag: 'BSC Chain',
    status: 'upcoming',
    featured: false,
    img: '/assets/metagame.png',
    description:
      'MetaGameSpace is a Tech Brand developing its own Gaming Metaverse. We have our first game Genesys being developed and the Genesys Tech Demo V1 is live on our website for the community.',
    time: 'TBA',
    startTime: 1645639200,
    finishTime: 1745725600,
    chainID: '56',
    chain: 'bsc',
    tokenDistribution: 100000000,
    tokenPrice: '0.0000001',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 200,
    receivedFund: 'TBA',
    twitterlink: 'https://twitter.com/MetaGameSpace',
    telegramlink: 'https://t.me/metagamespace',
    redditlink: '',
    instagramlink: '',
    websitelink: 'https://metagamespace.net/',
    auditLink: 'https://metagamespace.net/Meta_Audit.pdf',
    totalUsers: 100,
    symbol: 'METAGS',
    decimals: 9,
    allocationType: 'BNB',
    totalSupply: '10,000,000,000',
    accessType: 'Tiers/Public',
    about: [
      'MetaGameSpace is a Tech Brand developing its own Gaming Metaverse. We have our first game Genesys being developed and the Genesys Tech Demo V1 is live on our website for the community. ',
      'Genesys Tech Demo V2 incorporating some major updates as compared to V1 is being developed and it is going live before the IDO.',
      'We have a long list of 5+ Games going live inside our MetaGameSpace Gaming Metaverse. Some of them with their genres being:',
      'Meta Command - Top Down War Game Real Time Strategy Game (RTS) PC ',
      'KryoMeta - Android Multiplayer Online Battle Arena (MOBA) ',
      'Eddy Tech - Android Arcade Game',
      'BullDose - Android Simulation Game',
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: 'TBA',
    videolink: '/assets/video/metatags.mp4',
    contractAddress: null,
    soldOut: false,
    saleDate: 'TBA',
    ICOcompletePercentage: 0,
    allocationTokens: 100000,
    oneBNBprice: 10000000,
    raisedBNB: 0,
    userTokenalance: 100,
    userBNBbalance: 11,
    userInvested: 0,
    remainingallocation: 'TBA',
    claimableTokens: 100,
    youtube: false,
    tiltText: 'IDO',
  },
  {
    title: 'Flewup NFT Robots',
    type: 'static',
    id: 11,
    tag: 'BSC Chain',
    status: 'upcoming',
    featured: false,
    img: '/assets/Flewup.png',
    description:
      'Flewup will level up the world of Robotics by utilizing Blockchain and Metaverse technologies! Backed by years of experience and extensive knowledge, we are here to deliver a long-term game changing  project!',
    time: 'TBA',
    startTime: 1645639200,
    finishTime: 1745725600,
    chainID: '56',
    chain: 'bsc',
    tokenDistribution: 100000000,
    tokenPrice: 'TBA',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 1100,
    receivedFund: 'TBA',
    twitterlink: 'http://twitter.com/flewuprobots',
    telegramlink: 'http://t.me/flewup',
    redditlink: '',
    instagramlink: '',
    websitelink: 'https://flewup.com/',
    auditLink: 'https://metagamespace.net/Meta_Audit.pdf',
    totalUsers: 100,
    symbol: 'TBA',
    decimals: 'TBA',
    allocationType: 'BNB',
    totalSupply: '100,000,000,000',
    accessType: 'Tiers/Public',
    about: [
      'Flewup will level up the world of Robotics by utilizing Blockchain and Metaverse technologies! Backed by years of experience and extensive knowledge, we are here to deliver a long-term game changing  project!',
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: 'TBA',
    videolink: '/assets/video/Flewup.mp4',
    contractAddress: null,
    soldOut: false,
    saleDate: 'TBA',
    ICOcompletePercentage: 0,
    allocationTokens: 100000,
    oneBNBprice: 10000000,
    raisedBNB: 0,
    userTokenalance: 100,
    userBNBbalance: 11,
    userInvested: 0,
    remainingallocation: 'TBA',
    claimableTokens: 100,
    youtube: false,
    tiltText: 'Incupad',
  },
  {
    title: 'BSCBay',
    type: 'ido',
    id: 22,
    tag: 'BSC Chain',
    status: 'closed',
    featured: false,
    img: './assets/bscbay.png',
    description:
      'BSCBay combines the previous successful instances and features of DEFI and integrates them to create a new paradigm. ',
    time: 'TBA',
    startTime: 1645192800,
    finishTime: 1645279200,
    chainID: '56',
    chain: 'bsc',
    tokenDistribution: 'TBA',
    tokenPrice: 'TBA',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 'TBA',
    receivedFund: 'TBA',
    twitterlink: 'https://twitter.com/bscbayofficial',
    telegramlink: 'https://t.me/bscbayofficial',
    redditlink: 'https://www.reddit.com/r/BSCBay',
    instagramlink: '',
    websitelink: 'https://bscbay.com/',
    auditLink:
      'https://github.com/solidproof/projects/blob/main/BSCBay/SmartContract_Audit_Solidproof_BSCBay.pdf',
    totalUsers: 100,
    symbol: 'IDO',
    decimals: 18,
    allocationType: 'BNB',
    totalSupply: '1,000,000,000',
    accessType: 'Partners Only',
    about: [
      'Earn 5% USDT reflections rewards every 4 hours automatically into your wallets.',
      'Unlike volume-based unsustainable projects, we ensure Sustainable Passive Income streams through Launchpad, DexPad and supporting tools whose income directly flows into investor rewards pool',
      'We will be launching services including LaunchPad, DexPad, Lockers, Token Minters, KYC, NFTs and Play to Earn games to ensure the investor pools never die.',
      'BSCBay is a blockchain innovation hub with a combination of LaunchPad and DexPad complimenting. It combines the previous successful instances and features of DEFI and integrates them to create a new paradigm; a revolution within an evolution.',
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: '0xaa3387B36a4aCd9D2c1326a7f10658d7051b73a6',
    videolink: '../../..//assets/bscbayvideo.mp4',
    contractAddress: '0x4b803DD894746E5c66812b1EBCaA1b63217c166a',
    soldOut: true,
    saleDate: "18 FEB' 22, 2:00 PM UTC",
    tiltText: 'IDO',
  },
  {
    title: 'BSCBay',
    type: 'normal',
    id: 1,
    tag: 'BSC Chain',
    status: 'closed',
    featured: false,
    img: './assets/bscbay.png',
    description:
      'BSCBay combines the previous successful instances and features of DEFI and integrates them to create a new paradigm. ',
    time: 'TBA',
    startTime: 1645192800,
    finishTime: 1645279200,
    chainID: '56',
    chain: 'bsc',
    tokenDistribution: 'TBA',
    tokenPrice: 'TBA',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 'TBA',
    receivedFund: 'TBA',
    twitterlink: 'https://twitter.com/bscbayofficial',
    telegramlink: 'https://t.me/bscbayofficial',
    redditlink: 'https://www.reddit.com/r/BSCBay',
    instagramlink: '',
    websitelink: 'https://bscbay.com/',
    auditLink:
      'https://github.com/solidproof/projects/blob/main/BSCBay/SmartContract_Audit_Solidproof_BSCBay.pdf',
    totalUsers: 100,
    symbol: 'BSCB',
    decimals: 18,
    allocationType: 'BNB',
    totalSupply: '1,000,000,000',
    accessType: 'Partners Only',
    about: [
      'Earn 5% USDT reflections rewards every 4 hours automatically into your wallets.',
      'Unlike volume-based unsustainable projects, we ensure Sustainable Passive Income streams through Launchpad, DexPad and supporting tools whose income directly flows into investor rewards pool',
      'We will be launching services including LaunchPad, DexPad, Lockers, Token Minters, KYC, NFTs and Play to Earn games to ensure the investor pools never die.',
      'BSCBay is a blockchain innovation hub with a combination of LaunchPad and DexPad complimenting. It combines the previous successful instances and features of DEFI and integrates them to create a new paradigm; a revolution within an evolution.',
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: '0xaa3387B36a4aCd9D2c1326a7f10658d7051b73a6',
    videolink: '../../..//assets/bscbayvideo.mp4',
    contractAddress: '0x4b803DD894746E5c66812b1EBCaA1b63217c166a',
    soldOut: true,
    saleDate: "18 FEB' 22, 2:00 PM UTC",
    tiltText: '',
  },

  {
    title: 'BSCBay',
    type: 'normal',
    id: 2,
    tag: 'BSC Chain',
    status: 'upcoming',
    featured: false,
    img: './assets/bscbay.png',
    description:
      'BSCBay combines the previous successful instances and features of DEFI and integrates them to create a new paradigm. ',
    time: 'TBA',
    startTime: 1645639200,
    finishTime: 1645725600,
    chainID: '56',
    chain: 'bsc',
    tokenDistribution: 'TBA',
    tokenPrice: 'TBA',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 'TBA',
    receivedFund: 'TBA',
    twitterlink: 'https://twitter.com/bscbayofficial',
    telegramlink: 'https://t.me/bscbayofficial',
    redditlink: 'https://www.reddit.com/r/BSCBay',
    instagramlink: '',
    websitelink: 'https://bscbay.com/',
    auditLink:
      'https://github.com/solidproof/projects/blob/main/BSCBay/SmartContract_Audit_Solidproof_BSCBay.pdf',
    totalUsers: 100,
    symbol: 'BSCB',
    decimals: 18,
    allocationType: 'BNB',
    totalSupply: '1,000,000,000',
    accessType: 'Whitelist/Public',
    about: [
      'Earn 5% USDT reflections rewards every 4 hours automatically into your wallets.',
      'Unlike volume-based unsustainable projects, we ensure Sustainable Passive Income streams through Launchpad, DexPad and supporting tools whose income directly flows into investor rewards pool',
      'We will be launching services including LaunchPad, DexPad, Lockers, Token Minters, KYC, NFTs and Play to Earn games to ensure the investor pools never die.',
      'BSCBay is a blockchain innovation hub with a combination of LaunchPad and DexPad complimenting. It combines the previous successful instances and features of DEFI and integrates them to create a new paradigm; a revolution within an evolution.',
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: '0xaa3387B36a4aCd9D2c1326a7f10658d7051b73a6',
    videolink: '../../..//assets/bscbayvideo.mp4',
    contractAddress: '0x87f3fce34c239466502ecb5481bbb5bd08c64656',
    soldOut: true,
    saleDate: "23 FEB' 22, 6:00 PM UTC",
  },
  {
    title: 'Normal New BSCBay',
    type: 'normal',
    id: 2,
    tag: 'BSC Chain',
    status: 'upcoming',
    featured: false,
    img: './assets/bscbay.png',
    description:
      'BSCBay combines the previous successful instances and features of DEFI and integrates them to create a new paradigm. ',
    time: 'TBA',
    startTime: 1646565504,
    finishTime: 1646567504,
    chainID: '56',
    chain: 'bsc',
    tokenDistribution: 'TBA',
    tokenPrice: 'TBA',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 'TBA',
    receivedFund: 'TBA',
    twitterlink: 'https://twitter.com/bscbayofficial',
    telegramlink: 'https://t.me/bscbayofficial',
    redditlink: 'https://www.reddit.com/r/BSCBay',
    instagramlink: '',
    websitelink: 'https://bscbay.com/',
    auditLink:
      'https://github.com/solidproof/projects/blob/main/BSCBay/SmartContract_Audit_Solidproof_BSCBay.pdf',
    totalUsers: 100,
    symbol: 'BSCB',
    decimals: 18,
    allocationType: 'BNB',
    totalSupply: '1,000,000,000',
    accessType: 'Whitelist/Public',
    about: [
      'Earn 5% USDT reflections rewards every 4 hours automatically into your wallets.',
      'Unlike volume-based unsustainable projects, we ensure Sustainable Passive Income streams through Launchpad, DexPad and supporting tools whose income directly flows into investor rewards pool',
      'We will be launching services including LaunchPad, DexPad, Lockers, Token Minters, KYC, NFTs and Play to Earn games to ensure the investor pools never die.',
      'BSCBay is a blockchain innovation hub with a combination of LaunchPad and DexPad complimenting. It combines the previous successful instances and features of DEFI and integrates them to create a new paradigm; a revolution within an evolution.',
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: '0xaa3387B36a4aCd9D2c1326a7f10658d7051b73a6',
    videolink: '../../..//assets/bscbayvideo.mp4',
    contractAddress: '0x87f3fce34c239466502ecb5481bbb5bd08c64656',
    soldOut: true,
    saleDate: "23 FEB' 22, 6:00 PM UTC",
  },
];
