export const poolData = [
  {
    title: "BSCBAY",
    tag: "BSC Chain",
    status: "upcoming",
    featured: true,
    img: "./assets/bscbay.png",
    description:
      "BSCBAY is the next step in the evolution of DEFI. It combines the previous successful instances and features of DEFI and integrates them to create a new paradigm; a revolution within an evolution.",
    time: "48 Hours",
    chainID: "56",
    tokenDistribution: "0.01",
    tokenPrice: 0.000002857,
    minAllocation: 0.1,
    maxAllocation: 5,
    softCap: 20,
    hardCap: 200,
    receivedFund: 50000,
    TwitterLink: "",
    telegramLink: "https://t.me/bscbayofficial",
    redditLink: "",
    instagramLink: "",
    websitelink: "",
    totalUsers: 100,
    symbol: "BSCB",
    decimals: 18,
    allocationType: "BNB",
    totalSupply: 70000000,
    accessType: "Private",
    about: ["BSCBAY", "First Ico"],
    inputTokenaddress: "0xEC74F6747d5718A06785B84D45b26Ec136C7fca9",
    outputTokenaddress: "0xEC74F6747d5718A06785B84D45b26Ec136C7fca9",
  },
 
];
