export const poolData = [
  {
    title: 'BSCBay',
    tag: 'BSC Chain',
    status: 'upcoming',
    featured: true,
    img: './assets/bscbay.png',
    description:
      'BSCBay combines the previous successful instances and features of DEFI and integrates them to create a new paradigm. ',
    time: 'TBA',
    startTime: 1645192800,
    finishTime: 1645279200,
    chainID: '56',
    tokenDistribution: 'TBA',
    tokenPrice: 'TBA',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 'TBA',
    receivedFund: 'TBA',
    twitterlink: 'https://twitter.com/bscbayofficial',
    telegramlink: 'https://t.me/bscbayofficial',
    redditlink: 'https://www.reddit.com/r/BSCBay',
    instagramlink: '',
    websitelink: 'https://bscbay.com/',
    auditLink:
      'https://github.com/solidproof/projects/blob/main/BSCBay/SmartContract_Audit_Solidproof_BSCBay.pdf',
    totalUsers: 100,
    symbol: 'BSCB',
    decimals: 18,
    allocationType: 'BNB',
    totalSupply: '1,000,000,000',
    accessType: 'Partners Only',
    about: [
      'Earn 5% USDT reflections rewards every 4 hours automatically into your wallets.',
      'Unlike volume-based unsustainable projects, we ensure Sustainable Passive Income streams through Launchpad, DexPad and supporting tools whose income directly flows into investor rewards pool',
      'We will be launching services including LaunchPad, DexPad, Lockers, Token Minters, KYC, NFTs and Play to Earn games to ensure the investor pools never die.',
      'BSCBay is a blockchain innovation hub with a combination of LaunchPad and DexPad complimenting. It combines the previous successful instances and features of DEFI and integrates them to create a new paradigm; a revolution within an evolution.',
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: '0xaa3387B36a4aCd9D2c1326a7f10658d7051b73a6',
    videolink: '../../..//assets/bscbayvideo.mp4',
    contractAddress: '0x4b803DD894746E5c66812b1EBCaA1b63217c166a',
    soldout: false,
  },
];

// 0xF944C1438C2903e593200d54885204DF181DBBf3
