export const dexpaddata = [
  {
    title: 'BlockStar ',
    id: 1,
    tag: 'BSC Chain',
    status: 'Upcoming',
    featured: false,
    img: './assets/blockstar.png',
    description:
      'BlockStar will change the Social Media landscape forever. Full KYC and Audited done Through TRU-AUDIT The First Social Media Platform built on blockchain technology! Come Join the Fun!!! BlockStar.site',
    time: 'TBA',
    startTime: 1646316000,
    finishTime: 1646402400,
    chainID: '56', 
    chain: 'bsc',
    tokenDistribution: 'TBA',
    tokenPrice: 'TBA',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 'TBA',
    receivedFund: 'TBA',
    twitterlink: 'https://twitter.com/BlockStar_BST',
    telegramlink: 'https://t.me/BlockStar_Social_Media',
    redditlink: '',
    instagramlink: '',
    websitelink: 'https://blockstar.site/',
    auditLink:
      '',
    kycLink:
      'https://blockstar.site/page/view-album-media?id=2140',
    totalUsers: 100,
    symbol: 'BCT',
    decimals: 9,
    allocationType: 'BNB',
    totalSupply: '100,000,000',
    accessType: 'Private/Whitelist',
    about: [
      'BlockStar will change the Social Media landscape forever. Full KYC and Audited done Through TRU-AUDIT The First Social Media Platform built on blockchain technology! Come Join the Fun!!! BlockStar.site'
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: '0x6b2Bf0d3dfF08D32460D043851CCecc05BF8E197',
    videolink: '',
    contractAddress: '0x4b803DD894746E5c66812b1EBCaA1b63217c166a',
    soldOut: false,
    saleDate: "1 March' 22, 2:00 PM UTC",
  },
];
