export const staticData = [
  {
    title: 'MetaGameSpace',
    id: 10,
    tag: 'BSC Chain',
    status: 'upcoming',
    featured: false,
    img: '/assets/metagame.png',
    description:
      'MetaGameSpace is a Tech Brand developing its own Gaming Metaverse. We have our first game Genesys being developed and the Genesys Tech Demo V1 is live on our website for the community.',
    time: 'TBA',
    startTime: 1645639200,
    finishTime: 1745725600,
    chainID: '56',
    chain: 'bsc',
    tokenDistribution: 100000000,
    tokenPrice: '0.0000001',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 200,
    receivedFund: 'TBA',
    twitterlink: 'https://twitter.com/MetaGameSpace',
    telegramlink: 'https://t.me/metagamespace',
    redditlink: '',
    instagramlink: '',
    websitelink: 'https://metagamespace.net/',
    auditLink: 'https://metagamespace.net/Meta_Audit.pdf',
    totalUsers: 100,
    symbol: 'METAGS',
    decimals: 9,
    allocationType: 'BNB',
    totalSupply: '10,000,000,000',
    accessType: 'Tiers/Public',
    about: [
      'MetaGameSpace is a Tech Brand developing its own Gaming Metaverse. We have our first game Genesys being developed and the Genesys Tech Demo V1 is live on our website for the community. ',
      'Genesys Tech Demo V2 incorporating some major updates as compared to V1 is being developed and it is going live before the IDO.',
      'We have a long list of 5+ Games going live inside our MetaGameSpace Gaming Metaverse. Some of them with their genres being:',
      'Meta Command - Top Down War Game Real Time Strategy Game (RTS) PC ',
      'KryoMeta - Android Multiplayer Online Battle Arena (MOBA) ',
      'Eddy Tech - Android Arcade Game',
      'BullDose - Android Simulation Game',
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: 'TBA',
    videolink: '/assets/video/metatags.mp4',
    contractAddress: null,
    soldOut: false,
    saleDate: 'TBA',
    ICOcompletePercentage: 0,
    allocationTokens: 100000,
    oneBNBprice: 10000000,
    raisedBNB: 0,
    userTokenalance: 100,
    userBNBbalance: 11,
    userInvested: 0,
    remainingallocation: 'TBA',
    claimableTokens: 100,
    youtube: false,
    tiltText: 'ICO',
  },

  {
    title: 'MetaGameSpace2',
    id: 11,
    tag: 'BSC Chain',
    status: 'upcoming',
    featured: false,
    img: '/assets/metagame.png',
    description:
      'MetaGameSpace is a Tech Brand developing its own Gaming Metaverse. We have our first game Genesys being developed and the Genesys Tech Demo V1 is live on our website for the community.',
    time: 'TBA',
    startTime: 1645639200,
    finishTime: 1745725600,
    chainID: '56',
    chain: 'bsc',
    tokenDistribution: 100000000,
    tokenPrice: '0.0000001',
    minAllocation: 'TBA',
    maxAllocation: 'TBA',
    softCap: 'TBA',
    hardCap: 200,
    receivedFund: 'TBA',
    twitterlink: 'https://twitter.com/MetaGameSpace',
    telegramlink: 'https://t.me/metagamespace',
    redditlink: '',
    instagramlink: '',
    websitelink: 'https://metagamespace.net/',
    auditLink: 'https://metagamespace.net/Meta_Audit.pdf',
    totalUsers: 100,
    symbol: 'METAGS',
    decimals: 9,
    allocationType: 'BNB',
    totalSupply: '10,000,000,000',
    accessType: 'Tiers/Public',
    about: [
      'MetaGameSpace is a Tech Brand developing its own Gaming Metaverse. We have our first game Genesys being developed and the Genesys Tech Demo V1 is live on our website for the community. ',
      'Genesys Tech Demo V2 incorporating some major updates as compared to V1 is being developed and it is going live before the IDO.',
      'We have a long list of 5+ Games going live inside our MetaGameSpace Gaming Metaverse. Some of them with their genres being:',
      'Meta Command - Top Down War Game Real Time Strategy Game (RTS) PC ',
      'KryoMeta - Android Multiplayer Online Battle Arena (MOBA) ',
      'Eddy Tech - Android Arcade Game',
      'BullDose - Android Simulation Game',
    ],
    inputTokenaddress: 'TBA',
    outputTokenaddress: 'TBA',
    videolink: 'https://www.youtube.com/embed/R8JES-jufPs',
    contractAddress: null,
    soldOut: false,
    saleDate: 'TBA',
    ICOcompletePercentage: 0,
    allocationTokens: 100000,
    oneBNBprice: 10000000,
    raisedBNB: 0,
    userTokenalance: 100,
    userBNBbalance: 11,
    userInvested: 0,
    remainingallocation: 'TBA',
    claimableTokens: 100,
    youtube: true,
  },

  // {
  //   title: 'MetaGameSpace',   metatags.mp4
  //   id: 11,
  //   tag: 'BSC Chain',
  //   status: 'upcoming',
  //   featured: false,
  //   img: '/assets/metatags.png',
  //   description:
  //     'MetaGameSpace is a Tech Brand developing its own Gaming Metaverse. We have our first game Genesys being developed and the Genesys Tech Demo V1 is live on our website for the community.',
  //   time: 'TBA',
  //   startTime: 1645639200,
  //   finishTime: 1645725600,
  //   chainID: '56',
  //   chain: 'bsc',
  //   tokenDistribution: 100000000,
  //   tokenPrice: 1000,
  //   minAllocation: 2.5,
  //   maxAllocation: 5,
  //   softCap: 'TBA',
  //   hardCap: 1,
  //   receivedFund: 'TBA',
  //   twitterlink: 'https://twitter.com/bscbayofficial',
  //   telegramlink: 'https://t.me/bscbayofficial',
  //   redditlink: 'https://www.reddit.com/r/BSCBay',
  //   instagramlink: '',
  //   websitelink: 'https://bscbay.com/',
  //   auditLink:
  //     'https://github.com/solidproof/projects/blob/main/BSCBay/SmartContract_Audit_Solidproof_BSCBay.pdf',
  //   totalUsers: 100,
  //   symbol: 'BSCB',
  //   decimals: 18,
  //   allocationType: 'BNB',
  //   totalSupply: '1,000,000,000',
  //   accessType: 'Whitelist/Public',
  //   about: [
  //     'Earn 5% USDT reflections rewards every 4 hours automatically into your wallets.',
  //     'Unlike volume-based unsustainable projects, we ensure Sustainable Passive Income streams through Launchpad, DexPad and supporting tools whose income directly flows into investor rewards pool',
  //     'We will be launching services including LaunchPad, DexPad, Lockers, Token Minters, KYC, NFTs and Play to Earn games to ensure the investor pools never die.',
  //     'BSCBay is a blockchain innovation hub with a combination of LaunchPad and DexPad complimenting. It combines the previous successful instances and features of DEFI and integrates them to create a new paradigm; a revolution within an evolution.',
  //   ],
  //   inputTokenaddress: 'TBA',
  //   outputTokenaddress: 'TBA',
  //   videolink: '../../..//assets/bscbayvideo.mp4',
  //   contractAddress: null,
  //   soldOut: true,
  //   saleDate: "23 FEB' 22, 6:00 PM UTC",
  //   ICOcompletePercentage: 0,
  //   allocationTokens: 100000,
  //   oneBNBprice: 1000,
  //   raisedBNB: 100,
  //   userTokenalance: 100,
  //   userBNBbalance: 11,
  //   userInvested: 100,
  //   remainingallocation: 1200,
  //   claimableTokens: 100,
  // },

  // {
  //   title: 'MetaGameSpace',
  //   id: 3,
  //   tag: 'BSC Chain',
  //   status: 'upcoming',
  //   featured: false,
  //   img: './assets/metatags.png',
  //   description:
  //     'MetaGameSpace is a Tech Brand developing its own Gaming Metaverse. We have our first game Genesys being developed and the Genesys Tech Demo V1 is live on our website for the community.',
  //   time: 'TBA',
  //   startTime: 1645639200,
  //   finishTime: 1645725600,
  //   chainID: '56',
  //   chain: 'bsc',
  //   tokenDistribution: 'TBA',
  //   tokenPrice: 'TBA',
  //   minAllocation: 'TBA',
  //   maxAllocation: 'TBA',
  //   softCap: 'TBA',
  //   hardCap: 'TBA',
  //   receivedFund: 'TBA',
  //   twitterlink: 'https://twitter.com/MetaGameSpace',
  //   telegramlink: 'https://t.me/metagamespace',
  //   redditlink: '',
  //   instagramlink: '',
  //   websitelink: 'https://metagamespace.net/',
  //   auditLink:
  //     'https://metagamespace.net/Meta_Audit.pdf',
  //   totalUsers: 100,
  //   symbol: 'METAGS',
  //   decimals: 9,
  //   allocationType: 'BNB',
  //   totalSupply: '10,000,000,000',
  //   accessType: 'Whitelist/Public',
  //   about: [
  //     'MetaGameSpace is a Tech Brand developing its own Gaming Metaverse. We have our first game Genesys being developed and the Genesys Tech Demo V1 is live on our website for the community. ',
  //    "Genesys Tech Demo V2 incorporating some major updates as compared to V1 is being developed and it is going live before the IDO.",
  //    "We have a long list of 5+ Games going live inside our MetaGameSpace Gaming Metaverse. Some of them with their genres being:",
  //    "Meta Command - Top Down War Game Real Time Strategy Game (RTS) PC ",
  //    "KryoMeta - Android Multiplayer Online Battle Arena (MOBA) ",
  //    "Eddy Tech - Android Arcade Game",
  //    "BullDose - Android Simulation Game",
  //   ],
  //   inputTokenaddress: 'TBA',
  //   outputTokenaddress: '0xBB77D0A1181E38a0374Dc6891E2847C2b61B3545',
  //   videolink: 'https://www.youtube.com/watch?v=Cgq9D79e24I',
  //   contractAddress: '0x87f3fce34c239466502ecb5481bbb5bd08c64656',
  //   soldOut: false,
  //   saleDate: "23 FEB' 22, 6:00 PM UTC",
  //   ICOcompletePercentage: 0,
  //   allocationTokens: 100000,
  //   oneBNBprice: 1000,
  //   raisedBNB: 100,
  //   userTokenalance: 100,
  //   userBNBbalance: 11,
  //   userInvested: 100,
  //   remainingallocation: 1200,
  //   claimableTokens: 100,

  // },
];
